"""Fix foreign keys and relationships

Revision ID: 217dc21b7d12
Revises: 6bc1569c4493
Create Date: 2024-07-18 16:16:57.710122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '217dc21b7d12'
down_revision: Union[str, None] = '6bc1569c4493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_tickets_id', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_loyalty_programs_id', table_name='loyalty_programs')
    op.drop_index('ix_promotions_id', table_name='promotions')
    op.drop_index('ix_reviews_id', table_name='reviews')
    op.alter_column('user_preferences', 'preferred_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_preferences', 'preferred_currency',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    op.drop_column('user_preferences', 'email_notifications')
    op.drop_column('user_preferences', 'sms_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    op.alter_column('user_preferences', 'preferred_currency',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_preferences', 'preferred_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('ix_reviews_id', 'reviews', ['id'], unique=False)
    op.create_index('ix_promotions_id', 'promotions', ['id'], unique=False)
    op.create_index('ix_loyalty_programs_id', 'loyalty_programs', ['id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='support_tickets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_tickets_pkey')
    )
    op.create_index('ix_support_tickets_id', 'support_tickets', ['id'], unique=False)
    # ### end Alembic commands ###
